version: '3.1'

services:
  go:
    build: .
    image: go-coordinate-converter
    volumes:
      - $TEMP:/go/src/github.com/osu-mist/coordinate-converter
    working_dir: /go/src/github.com/osu-mist/coordinate-converter
    command: go build -v
    network_mode: "host"
  cs2cs:
    image: "osgeo/proj"
    depends_on:
      - go
    environment:
      - URL
    volumes:
      - $TEMP:/tmp
    working_dir: /tmp
    command: sh -c /tmp/run.sh
    network_mode: "host"
